--- @class Gears
---
--- @class Xresources
--- @field apply_dpi Dpi
--
---
---
--- @class Wibox
--- @field container table
--- @field widget fun(table): Widget
---
---
--- @class Awful
--- @field screen Screen
--- @field popup fun(x: table)
--- @field placement table
--- @field key fun(table, string, fun, table ): Key[]
--- @field button fun(table, number, fun, fun): table
---
---
--- @class Naughty
---
---
--- @class Ruled
---
---
--- @class Menubar
---
---
--- @class Notification
---
---
--- @class Client
---
---
--- @class Widget
---
---
--- @class Screen
--- @field index number
--- @field focused fun()
---
---
--- @class BaseWidget
--- @field new fun(s: Screen)
--- @field widget Widget
---
--- @class Dpi
---
--- @class MacroUpdatable : BaseWidget
--- @field update fun(self: MacroUpdatable, isOn:boolean)
---
---
--- @class Icon
--- @field widget fun(color: string):Widget A field that contains prepared widget
--- @field path string path to the icon
---

--- @class KeybindingsInit
--- @field init fun(keybinds)

--- @class Initializable
--- @field isInitialized boolean
--- @field init fun()

--- @class Key

